apiVersion: v1
kind: Namespace
metadata:
  name: demo
  labels:
    mesh: demo-mesh
    gateway: ingress-gw
    appmesh.k8s.aws/sidecarInjectorWebhook: enabled
---
apiVersion: appmesh.k8s.aws/v1beta2
kind: Mesh
metadata:
  name: demo-mesh
spec:
  namespaceSelector:
    matchLabels:
      mesh: demo-mesh
